name: pratyaysh

services:
  app:
    image: ghcr.io/pratyay360/pratyaysh:latest
    container_name: pratyaysh
    volumes:
      - ./.ssh:/.ssh:z
    env_file:
      - .env
    restart: unless-stopped
