name: pratyaysh

services:
  app:
    image: ghcr.io/pratyay360/pratyaysh:latest
    container_name: pratyaysh
    volumes:
      - ./.ssh:/.ssh:z
    restart: unless-stopped
  cloudflared:
    image: docker.io/cloudflare/cloudflared:latest
    restart: unless-stopped
    command: tunnel --no-autoupdate run
    env_file:
      - .env
    depends_on:
      - app
