[tools]
golines = "latest"
go = "latest"
sops = "latest"
jqp = "latest"
golangci-lint = "latest"
golangci-lint-langserver = "latest"
"npm:sandbox" = "latest"

[tasks]
build = "go build"
clean = "go clean"
